/*
 * Code generated by maegi. DO NOT EDIT.
 */

export const body1 = {
  desktop: {
    fontFamily: "Menlo",
    fontWeight: 400,
    fontSize: 16,
    letterSpacing: 0,
    lineHeightPx: 20,
    opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
  },
  mobile: {
    fontFamily: "Menlo",
    fontWeight: 400,
    fontSize: 14,
    letterSpacing: 0,
    lineHeightPx: 18,
    opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
  },
} as const;

export const h1 = {
  fontFamily: "Menlo",
  fontWeight: 700,
  fontSize: 21,
  letterSpacing: 0,
  lineHeightPx: 36,
  opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
} as const;

export const h2 = {
  fontFamily: "Menlo",
  fontWeight: 700,
  fontSize: 18,
  letterSpacing: 0,
  lineHeightPx: 32,
  opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
} as const;

