/*
 * Code generated by maegi. DO NOT EDIT.
 */

export const body1 = {
  desktop: {
    fontFamily: "Menlo",
    fontWeight: 400,
    fontSize: 14,
    letterSpacing: 0,
    lineHeightPx: 24.219999313354492,
    opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
  },
  mobile: {
    fontFamily: "Menlo",
    fontWeight: 400,
    fontSize: 14,
    letterSpacing: 0,
    lineHeightPx: 24.219999313354492,
    opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
  },
} as const;

export const h1 = {
  fontFamily: "Menlo",
  fontWeight: 700,
  fontSize: 21,
  letterSpacing: 0.42,
  lineHeightPx: 36,
  opentypeFlags: { NUMR: 1, LIGA: 0, LNUM: 1, PNUM: 1 },
} as const;

export const h2 = {
  fontFamily: "Menlo",
  fontWeight: 700,
  fontSize: 16,
  letterSpacing: 0,
  lineHeightPx: 27,
  opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
} as const;

export const h3 = {
  fontFamily: "Menlo",
  fontWeight: 700,
  fontSize: 12.600000381469727,
  letterSpacing: 0,
  lineHeightPx: 21.735000610351562,
  opentypeFlags: { NUMR: 1, KERN: 0, LNUM: 1, PNUM: 1 },
} as const;

