import * as fs from "node:fs";
import * as path from "node:path";
import * as svgr from "@svgr/core";
import svgrPluginJsx from "@svgr/plugin-jsx";
import svgrPluginSvgo from "@svgr/plugin-svgo";
import { mkdirp } from "mkdirp";
import type { Icon } from "./types";

export * from "./types";

export function toCamelCase(x: string) {
  return `_${x.replace(/^ic_/, "")}`.replace(/^([A-Z])|[\s-_](\w)/g, (_match, p1, p2) =>
    p2 ? p2.toUpperCase() : p1.toLowerCase(),
  );
}

export function parseIconName(s: string) {
  const sizeMatch = s.match(/ic_(.*)_(\d+)dp(\.svg)?$/);
  if (!sizeMatch) {
    return undefined;
  }

  return {
    id: path.basename(s, ".svg"),
    name: toCamelCase(path.basename(s, ".svg").replace(/_(\d+)dp$/, "")),
    size: sizeMatch ? +sizeMatch[2] : 0,
  };
}

export async function generate(
  filename: string,
  f: (_: (str: string) => Promise<void>) => Promise<void>,
): Promise<void> {
  const stream = fs.createWriteStream(filename);

  stream.write(`/*\n`);
  stream.write(` * Code generated by maegi. DO NOT EDIT.\n`);
  stream.write(` */\n`);
  stream.write(`\n`);

  await f(async (str) => {
    stream.write(str);
  });

  return new Promise((resolve) => stream.end(resolve));
}

/**
 * Returns a function which is used to generate a React icon module (ie. a ES module
 * which exports a bunch of icons).
 */
export function writeIconModule(base: string) {
  return async ([name, instances]: [string, Icon[]]) => {
    await mkdirp(path.join(base, name));
    await generate(path.join(base, name, "index.tsx"), async (write) => {
      await write(`import React from "react";\n`);
      await write(`\n`);

      const sortedInstances = [...instances].sort((a, b) => a.size - b.size);
      for (const icon of sortedInstances) {
        await write(`${await iconCode(icon)}\n`);
        await write(`\n`);
      }

      await write(
        `export const __descriptor_${name} = {
    name: "${name}",
    instances: [
      ${sortedInstances
        .map(({ size }) => `{ size: ${size || `"responsive"`}, Component: ${name}${size || ""} }`)
        .join(",")}
    ]
  } as const;
  `,
      );
    });
  };
}

/**
 * Convert an Icon into React code.
 */
export async function iconCode({ name, size, src }: Icon): Promise<string> {
  const options: svgr.Config = {
    template({ componentName, jsx }, { tpl }) {
      return tpl`
        export const ${componentName} = (props: React.SVGProps<SVGSVGElement>) => ${jsx};
      `;
    },
    typescript: true,
    plugins: [svgrPluginSvgo, svgrPluginJsx],
    svgoConfig: {
      multipass: true,
      plugins: [
        /*
         * It is important to keep the 'convertColors' plugin before
         * 'preset-default'.
         *
         * The 'preset-default' plugin includes 'removeUnknownsAndDefaults',
         * which removes any fill/stroke attributes that are set to their
         * default (eg. fill="#000"). If the 'convertColors' plugin comes
         * after, it doesn't have a chance to replace those fill/stroke
         * colors with currentColor.
         */
        {
          name: "convertColors",
          params: { currentColor: true },
        },

        {
          name: "preset-default",
          params: {
            overrides: {
              removeViewBox: false,
            },
          },
        },
        {
          name: "removeAttrs",
          params: { attrs: "(xmlns.*)" },
        },
        "sortAttrs",
      ],
    },
  };

  return svgr.transform(src, options, {
    componentName: `${name}${size}`,
  });
}
