/*
 * Code generated by maegi. DO NOT EDIT.
 */

import React from "react";

export const Letter24 = React.memo < React.SVGProps < SVGSVGElement >> (props => <svg width={24} height={24} viewBox="0 0 24 24" {...props}><path fill="currentColor" fillRule="evenodd" d="M24 3v18H0V3zm-2 3.345-10 9L2 6.346V19h20zM20.504 5H3.495L12 12.654z" /></svg>);

export const __descriptor_Letter = {
    name: "Letter",
    instances: [
      { size: 24, Component: Letter24 }
    ]
  } as const;
  