/*
 * Code generated by maegi. DO NOT EDIT.
 */

import React from "react";

export const Lock40 = React.memo<React.SVGProps<SVGSVGElement>>((props) => (
  <svg width={40} height={40} viewBox="0 0 40 40" {...props}>
    <g fill="none" fillRule="evenodd">
      <path stroke="currentColor" strokeWidth={2} d="M12 17a1 1 0 00-1 1v12a1 1 0 001 1h16a1 1 0 001-1V18a1 1 0 00-1-1H12z" />
      <path fill="currentColor" d="M14 13h2v3h-2z" />
      <path stroke="currentColor" strokeWidth={2} d="M25 13a5 5 0 00-10 0" />
      <path fill="currentColor" d="M24 13h2v3h-2z" />
    </g>
  </svg>
));

export const __descriptor_Lock = {
  name: "Lock",
  instances: [{ size: 40, Component: Lock40 }],
} as const;
